from typing import Any, Optional

def begin(name: str, open: Optional[Any] = None, flags: int = 0) -> bool: ...
def end() -> None: ...
def button(label: str, width: float = 0.0, height: float = 0.0) -> bool: ...
def checkbox(label: str, v: bool) -> bool: ...
def slider_float(label: str, v: float, v_min: float, v_max: float) -> float: ...
def text(text: str) -> None: ...
def same_line() -> None: ...
def separator() -> None: ...
def spacing() -> None: ...
