#pragma once

#include <cstddef>
#include <cstdint>
#ifdef DNA_DEPRECATED_ALLOW
#  define DNA_DEPRECATED
#else
#  if defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER)
#    define DNA_DEPRECATED [[deprecated]]
#  else
#    define DNA_DEPRECATED
#  endif
#endif


#if defined(__GNUC__) || defined(__clang__)
/* clang-format off */
#  define DNA_DEPRECATED_IGNORE(statement) \
    _Pragma("GCC diagnostic push") \
    _Pragma("GCC diagnostic ignored \"-Wdeprecated-declarations\"") \
    statement \
    _Pragma("GCC diagnostic pop")
/* clang-format on */
#else
#  define DNA_DEPRECATED_IGNORE(statement) statement
#endif

namespace vektor::dna {

#define MAX_NAME 64

void DNA_internal_memcpy(void *dst, const void *src, size_t size);
void DNA_internal_memzero(void *dst, size_t size);
void DNA_internal_swap(void *a, void *b, size_t size);

template<class T> class ShallowDataConstRef {
 public:
  constexpr explicit ShallowDataConstRef(const T &ref) : ref_(ref) {}

  inline const T *get_pointer() const
  {
    return &ref_;
  }

 private:
  const T &ref_;
};

class ShallowZeroInitializeTag {};

#define DNA_DEFINE_CXX_METHODS(class_name) \
  DNA_DEPRECATED_IGNORE(class_name() = default;) \
  ~class_name() = default; \
  /* Delete copy and assignment, which are not safe for resource ownership. */ \
  class_name(const class_name &other) = delete; \
  class_name((class_name) && other) noexcept = delete; \
  (class_name) &operator=(const class_name &other) = delete; \
  (class_name) &operator=((class_name) && other) = delete; \
  /* Support for shallow copy. */ \
  /* NOTE: Calling the default constructor works-around deprecated warning generated by GCC. */ \
  class_name(const dna::internal::ShallowDataConstRef<class_name> ref) : class_name() \
  { \
    DNA_internal_memcpy(this, ref.get_pointer(), sizeof(class_name)); \
  } \
  (class_name) &operator=(const dna::internal::ShallowDataConstRef<class_name> ref) \
  { \
    if (this != ref.get_pointer()) { \
      DNA_internal_memcpy(this, ref.get_pointer(), sizeof(class_name)); \
    } \
    return *this; \
  } \
  /* Create object which memory is filled with zeros. */ \
  (class_name)(const dna::internal::ShallowZeroInitializeTag /*tag*/) : class_name() \
  { \
    DNA_internal_memzero(this, sizeof(class_name)); \
  } \
  (class_name) &operator=(const dna::internal::ShallowZeroInitializeTag /*tag*/) \
  { \
    DNA_internal_memzero(this, sizeof(class_name)); \
    return *this; \
  }

template<typename T> [[nodiscard]] inline ShallowDataConstRef<T> shallow_copy(const T &other)
{
  return ShallowDataConstRef(other);
}

template<typename T> inline void shallow_copy_array(T *dst, const T *src, const int64_t size)
{
  DNA_internal_memcpy(dst, src, sizeof(T) * size_t(size));
}

/* DNA object initializer which leads to an object which underlying memory is filled with zeroes.
 */
[[nodiscard]] inline ShallowZeroInitializeTag shallow_zero_initialize()
{
  return {};
}

template<typename T> inline void shallow_swap(T &a, T &b)
{
  DNA_internal_swap(&a, &b, sizeof(T));
}

}  // namespace vektor::dna
